### ISSUE TITLE
`text` unusable due to TypeError

### ISSUE THREAD

**Issue by nonchip** [supermerill/Pyscad#6]
in https://github.com/supermerill/FreePySCAD/blob/master/freepyscad.py#L1846 you `list+str`.

**Comment by nonchip** [comment]
oh also if the `text` string is of length 0:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 12, in <module>
  File "/home/kyra/.config/SuperSlicer/scripts/FreePySCAD/freepyscad.py", line 135, in redraw
    node.create()
  File "/home/kyra/.config/SuperSlicer/scripts/FreePySCAD/freepyscad.py", line 246, in create
    action[0](*action[1])
  File "/home/kyra/.config/SuperSlicer/scripts/FreePySCAD/freepyscad.py", line 325, in create_childs
    enode.create()
  File "/home/kyra/.config/SuperSlicer/scripts/FreePySCAD/freepyscad.py", line 246, in create
    action[0](*action[1])
  File "/home/kyra/.config/SuperSlicer/scripts/FreePySCAD/freepyscad.py", line 325, in create_childs
    enode.create()
  File "/home/kyra/.config/SuperSlicer/scripts/FreePySCAD/freepyscad.py", line 246, in create
    action[0](*action[1])
  File "/home/kyra/.config/SuperSlicer/scripts/FreePySCAD/freepyscad.py", line 1863, in createText
    textComponents[0].removeObject(compo)
TypeError: argument 1 must be str, not FeaturePython
```

**Comment by supermerill** [comment]
First issue should be fixed.
i'll do something for the nop of the second issue.
